# Generated by Django 5.2.5 on 2025-08-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetail',
            name='delivery_time_in_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='revisions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='offerdetail',
            constraint=models.UniqueConstraint(condition=models.Q(('offer_type__isnull', True), _negated=True), fields=('offer', 'offer_type'), name='unique_offer_offer_type'),
        ),
    ]
